# Generated by Django 3.2 on 2022-06-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='Companies',
            new_name='Company',
        ),
        migrations.RenameModel(
            old_name='Owners',
            new_name='Owner',
        ),
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
        migrations.RenameModel(
            old_name='Sprints',
            new_name='Sprint',
        ),
    ]
