# Generated by Django 3.2 on 2022-06-20 23:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planner', '0005_auto_20220620_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.company')),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('sprint_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('starts_at', models.DateField(null=True)),
                ('ends_at', models.DateField(null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.project')),
            ],
        ),
        migrations.CreateModel(
            name='Emplyee',
            fields=[
                ('emplyee_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('client', 'CLIENT'), ('developer', 'DEVELOPER'), ('admin', 'ADMIN')], default='client', max_length=9)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='planner.company')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('planning', 'PLANNING'), ('in fe development', 'IN_FE_DEVELOPMENT'), ('in be development', 'IN_BE_DEVELOPMENT'), ('testing', 'TESTING'), ('completed', 'COMPLETED')], default='pending', max_length=30)),
                ('category', models.CharField(choices=[('bug', 'BUG'), ('feature', 'FEATURE'), ('change', 'CHANGE')], default='feature', max_length=30)),
                ('due_date', models.DateField(null=True)),
                ('task_size', models.CharField(choices=[('very small', 'VSMALL'), ('small', 'SMALL'), ('medium', 'MEDIUM'), ('large', 'LARGE'), ('very large', 'VLARGE')], default='medium', max_length=30)),
                ('sprint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.sprint')),
            ],
        ),
    ]
