# Generated by Django 3.2 on 2022-06-21 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_case_company_emplyee_project_sprint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='last_name',
        ),
    ]
