# Generated by Django 3.2 on 2022-06-22 12:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planner', '0009_auto_20220622_1223'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='User_Profile',
        ),
    ]
