# Generated by Django 3.2 on 2022-06-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0012_company_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
